### ISSUE TITLE
'An internal server error occurred' message.

### ISSUE THREAD

**Issue by NePeter** [luyadev/luya-module-cms#183] opened 2019-02-28 13:26 UTC
When one adds two characters to the domain name in browser address bar error message 'An internal server error occurred.' are displayed.

**Comment by nadar** [comment] 2019-02-28 14:37
This description of the problem is very vague, also i can not reproduce the problem: `http://demo.luya.io/xx` 

config? version? enabled YII_DEBUG?

**Comment by NePeter** [comment] 2019-02-28 15:41
For example https://peter.net.ru/ + any two characters except ru.
Site is single language (ru).
Standard config, only changed 'langShortCode' => 'ru'
'composition' => [
            'hidden' => true,
            'default' => ['langShortCode' => 'ru'], 
        ],
and added 
define(YII_DEBUG, false)

Modules version:
luyadev/luya-generic ver. 1.0.3.0
luya-module-admin ver. 1.2.3.1
luya-module-cms ver. 1.0.9.0
luya-core ver. 1.0.15.0

**Comment by nadar** [comment] 2019-03-01 14:30
Enabled yii debug so you will see a stack trace.

**Comment by NePeter** [comment] 2019-03-04 11:32
I enabled yii debug and there is log message:
![yii debugger_logmessage-1](https://user-images.githubusercontent.com/11742167/53730875-29404e80-3e8a-11e9-9e38-42f868a26441.png)

**Comment by NePeter** [comment] 2019-03-04 14:32
'An internal server error occurred' message appear only if debug mode is disabled.
In the Log Message is not nothing more.

**Comment by nadar** [comment] 2019-03-04 14:37
Yes but even when yii debug is disabled it should throw the message from the screenshot above. I will try to reproduce your problem with the given composition config. Is there something else you have modified or changed?

**Comment by NePeter** [comment] 2019-03-04 14:43
My config is:
defined('YII_ENV') or define('YII_ENV', 'prod');
//defined('YII_DEBUG') or define('YII_DEBUG', true);
define('YII_DEBUG', false);

$config = [
   
    'id' => 'myproject',
    
    'siteTitle' => "Peter's Project",
   
    'defaultRoute' => 'cms',
    
    'basePath' => dirname(__DIR__),
    'modules' => [
        
        'admin' => [
            'class' => 'luya\admin\Module',
            'secureLogin' => false, 
            'strongPasswordPolicy' => false, 
            'interfaceLanguage' => 'en', 
        ],
        
        'cms' => [
            'class' => 'luya\cms\frontend\Module',
            'contentCompression' => true, 
        ],
        
        'cmsadmin' => [
            'class' => 'luya\cms\admin\Module',
            'hiddenBlocks' => [],
            'blockVariations' => [],
        ],
    ],
    'components' => [
        
        'mail' => [
            'host' => null,
            'username' => null,
            'password' => null,
            'from' => null,
            'fromName' => null,
        ],
        
        'composition' => [
            'hidden' => true, 
            'default' => ['langShortCode' => 'ru'], 
        ],
        
        'cache' => [
            'class' => 'yii\caching\DummyCache', // use: yii\caching\FileCache
            //'class' => 'yii\caching\FileCache',
        ],
        
        'i18n' => [
            'translations' => [
                'app*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                ],
            ],
        ],
    ],
];

/*
if (YII_DEBUG) {
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = ['class' => 'yii\debug\Module', 'allowedIPs' => ['*']];
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = ['class' => 'yii\gii\Module', 'allowedIPs' => ['*']];
}
*/

return \yii\helpers\ArrayHelper::merge($config, require('env-prod-db.php'));

**Comment by nadar** [comment] 2019-03-04 14:44
And what does your language table (admin_lang) looks like? which language have you created, which is default?

**Comment by NePeter** [comment] 2019-03-04 14:53
Only one language Russian ru. It's default.

**Comment by nadar** [comment] 2021-04-13 10:13
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.

**Closed by nadar** 2021-04-13 10:13 UTC
Labels: bug:research, need more informations

**Comment by Taroxx** [comment] 2021-11-23 15:50
I have the same problem. 
Table admin_lang have one row. 
en is default.
custom 404 page created as module (like in tutorial)
This is stack trace

An Error occurred while handling another error:
yii\web\NotFoundHttpException: The requested language 'xx' does not exist in language table in /site/vendor/luyadev/luya-module-cms/src/Menu.php:709
Stack trace:
#0 /site/vendor/luyadev/luya-module-cms/src/Menu.php(322): luya\cms\Menu->loadLanguageContainer('xx')
#1 /site/vendor/luyadev/luya-module-cms/src/Menu.php(213): luya\cms\Menu->getLanguageContainer('xx')
#2 /site/vendor/luyadev/luya-module-cms/src/menu/Query.php(399): luya\cms\Menu->offsetGet('xx')
#3 /site/vendor/luyadev/luya-module-cms/src/frontend/Bootstrap.php(56): luya\cms\menu\Query->one()
#4 [internal function]: luya\cms\frontend\Bootstrap->luya\cms\frontend\{closure}(Object(luya\web\ErrorHandlerExceptionRenderEvent))
#5 /site/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Object(Closure), Object(luya\web\ErrorHandlerExceptionRenderEvent))
#6 /site/vendor/luyadev/luya-core/web/ErrorHandler.php(31): yii\base\Component->trigger('onBeforeExcepti...', Object(luya\web\ErrorHandlerExceptionRenderEvent))
#7 /site/vendor/yiisoft/yii2/base/ErrorHandler.php(135): luya\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#8 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#9 {main}
Previous exception:
yii\web\NotFoundHttpException: The requested language 'xx' does not exist in language table in /site/vendor/luyadev/luya-module-cms/src/frontend/controllers/DefaultController.php:125
Stack trace:
#0 [internal function]: luya\cms\frontend\controllers\DefaultController->actionIndex()
#1 /site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /site/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /site/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('index', Array)
#4 /site/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('cms/default/ind...', Array)
#5 /site/vendor/luyadev/luya-core/web/Application.php(48): yii\web\Application->handleRequest(Object(luya\web\Request))
#6 /site/vendor/yiisoft/yii2/base/Application.php(392): luya\web\Application->handleRequest(Object(luya\web\Request))
#7 /site/vendor/luyadev/luya-core/base/Boot.php(268): yii\base\Application->run()
#8 /site/vendor/luyadev/luya-core/base/Boot.php(208): luya\base\Boot->applicationWeb()
#9 /site/public_html/index.php(13): luya\base\Boot->run()
#10 {main}
